### ISSUE TITLE
Extracted information

### ISSUE THREAD

**Issue by Sharlikran** [LennartPiro/Destinations#10]
[DestExport.zip](https://github.com/LennartPiro/Destinations/files/4400320/DestExport.zip)
[DestExport2.zip](https://github.com/LennartPiro/Destinations/files/4400323/DestExport2.zip)
[DestExport3.zip](https://github.com/LennartPiro/Destinations/files/4549724/DestExport3.zip)

**Comment by Sharlikran** [comment]
I figured out for the most part how to add the data, thank you.

**Comment by LennartPiro** [comment]
Please add a pull request with the new data. Thanks!
