### ISSUE TITLE
Check compatibility with new API version

### ISSUE THREAD

**Issue by Shredder121** [LennartPiro/Destinations#2]
Now that Murkmire DLC launched along with a new API version, this addon should be checked.

**Comment by Shredder121** [comment]
Oh I see you have a branch already for that, my bad.
But I'll keep it open so you can close it when that's resolved.
Keep up the good work!

**Comment by LennartPiro** [comment]
Should be all good now, the commit https://github.com/LennartPiro/Destinations/commit/2e040f585654451351bdd1900ad54f6bbef1d293 should be on Minion soon as v3.1.1.
