### ISSUE TITLE
Addon not installing in its own folder

### ISSUE THREAD

**Issue by Shredder121** [LennartPiro/Destinations#4]
I noticed that the addon got extracted by minion in the root `AddOns` folder.
Are the line endings correct? I did see the latest commits did touch the metadata file, although I don't know whether Minion uses that or not.

Can you at least confirm you observe the same behavior? then I can check whether it's something I did.

**Comment by FHoulbreque** [comment]
I do confirm this issue. The add-on install into the base AddOn directory after the update making it not seen by TESO. I had to move back the files into Destinations folder

May I suggest the .zip file doesn't include the wrapper Directory? Probably it couldn't be anything else. And I can't check it out as I can't load the 3.1.4 from ESOUI as it is pending review by an Admin...

**Comment by LennartPiro** [comment]
Confirmed and already fixed, I have commented on this on esoui: https://www.esoui.com/downloads/fileinfo.php?id=667#comments
As soon as the admins release the update, everything will be fine.

**Comment by Shredder121** [comment]
Thanks for the quick reply, great work!

**Comment by FHoulbreque** [comment]
Thanks for the answer but... no, it will not be fine. If I take the master from GitHub and put it into the Destinations folder, it result in the game not finding MapPins Library... (and I moved Libs, data and pins directory into the Destinations one I created)

**Comment by LennartPiro** [comment]
> 
> 
> Thanks for the answer but... no, it will not be fine. If I take the master from GitHub and put it into the Destinations folder, it result in the game not finding MapPins Library... (and I moved Libs, data and pins directory into the Destinations one I created)

The version on master at that moment was not what I had uploaded to esoui.com. Now it is.

The fix is now available through esoui and Minion, so I will close this issue.
